feat: block api 요청사항 추가
dnd-side-project/dnd-8th-7-backend pull request #12
Opened 2023-02-22 13:11 UTC by rineeee

### summary

block api 수정 및 코드 전반 react

### change

- block api(block_id, task_id, review_id 추가)
- 유니코드 정규식
- dto 파일명
- cascade 설정 완료
- sql review 추가

2023-02-22 13:22 UTC, rineeee commented
테스트 때문에 막아놨던 security 설정 다시 돌려놨습니다.

2023-02-22 13:25 UTC, pasly0920 commented on src/main/java/com/dnd8th/util/validator/EmojiValidator.java
> +        return value.matches("[^\\p{L}]+");
해당 정규 표현식이 검증이 정확히 되나요? 일반적인 String도 통과하는 것 같아서요.

2023-02-22 13:32 UTC, pasly0920 requested changes
고생 많으셨습니다!

2023-02-22 13:32 UTC, pasly0920 commented on src/main/java/com/dnd8th/dao/ReviewFindDao.java
> +                .where(review.user.email.eq(email), review.date.eq(date))
review.user를 불러오는 과정이 암묵적 join으로 보이는데 이를 명시적 join으로 대체하는 것이 어떨까요? ex. fetchJoin

2023-02-22 13:32 UTC, pasly0920 commented on src/main/java/com/dnd8th/service/BlockService.java
>          String dateFormat = simpleDateFormat.format(targetDate);
이전에 추가한 DateParser를 사용해보시는 것도 괜찮을 것 같습니다.

2023-02-22 13:32 UTC, pasly0920 commented on src/main/java/com/dnd8th/service/BlockService.java
이 부분도 DateParser를 추가해보심이 어떠신가요

2023-02-22 13:37 UTC, rineeee commented on src/main/java/com/dnd8th/util/validator/EmojiValidator.java
> +        return value.matches("[^\\p{L}]+");
https://github.com/vdurmont/emoji-java 해당 라이브러리 사용할 예정입니다.

2023-02-22 13:38 UTC, rineeee commented
낼,, 추가할게요 인우님

2023-02-23 10:46 UTC, rineeee commented on src/main/java/com/dnd8th/util/validator/EmojiValidator.java
> +        return value.matches("[^\\p{L}]+");
e7b0499bd573af4235c7971ba2b18d954122317f

2023-02-23 11:05 UTC, rineeee commented on src/main/java/com/dnd8th/dao/ReviewFindDao.java
> +                .where(review.user.email.eq(email), review.date.eq(date))
이 부분이 아무리해도 잘 안되는 데 혹시 도움주실 수 있나요?

2023-02-23 11:05 UTC, rineeee commented on src/main/java/com/dnd8th/service/BlockService.java
>          String dateFormat = simpleDateFormat.format(targetDate);
d19bcf638ef210dfe41aa8e473e6c9af99de8fef

2023-02-23 11:05 UTC, rineeee commented on src/main/java/com/dnd8th/service/BlockService.java
d19bcf638ef210dfe41aa8e473e6c9af99de8fef

2023-02-23 15:35 UTC, pasly0920 commented on src/main/java/com/dnd8th/util/DateParser.java
> +        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
위의 parseDate에서도 SimpleDateFormat이 동일하게 사용되고 있는데 이를 static으로 설정하는 게 어떨까요?

2023-02-24 09:48 UTC, pasly0920 commented on src/main/java/com/dnd8th/dao/ReviewFindDao.java
> +                .where(review.user.email.eq(email), review.date.eq(date))
현재 배포 진행중이라 배포 진행이 끝난 뒤에 도움 드릴 수 있도록 하겠습니다

2023-02-25 03:44 UTC, rineeee commented on src/main/java/com/dnd8th/util/DateParser.java
> +        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
a10aa1f1e0c3fc3a587ea6373a82ace19cea5ac1

2023-02-25 05:21 UTC, pasly0920 approved these changes
고생하셨습니다

2023-02-25 05:31 UTC, merged